[build]
    base = "/"
    command = "ng build"
    publish = "dist/library-fe/browser"

    [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    from = " "
    to = "/home"
    status = 200

